### ISSUE TITLE
Error in MSA2dist::cds2aa  unused argument (return.cds = TRUE)

### ISSUE THREAD

**Issue by karthickbrlab** [kullrich/kakscalculator2#3]
HI..

how to solve this

K1 |> MSA2dist::cds2aa(shorten=TRUE, return.cds=TRUE) |> MSA2dist::dnastring2kaks(model = "YN")
Error in MSA2dist::cds2aa(K1, shorten = TRUE, return.cds = TRUE) : 
  unused argument (return.cds = TRUE)

  MSA2dist::dnastring2kaks(cds1, model = "YN")
Error in MSA2dist::dnastring2kaks(cds1, model = "YN") : 
  Error: input needs to be a DNAStringSet

**Comment by kullrich** [comment]
Hi, it seems that you have not installed the development version, to do so:
```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("MSA2dist")
```

**Comment by karthickbrlab** [comment]
Hi..

Installed it,
Does the ka/ks ratio be infinite?

I got quite different results in different models. Which one is a go to
model for chloroplast genes.

**Comment by kullrich** [comment]
Hi, yes, if e.g. there are only non-synonymous changes in a gene and no synonymous change.

You could try to compare the models against e.g. http://www.hyphy.org results or http://abacus.gene.ucl.ac.uk/software/paml.html to select a model that fits your data.

Here you would find a python script to run codeml:

https://github.com/kullrich/bio-scripts/blob/master/fasta/cds2codeml.py

Best regards

**Comment by karthickbrlab** [comment]
Well.. Then could we say the gene has obvious positive selection?

**Comment by kullrich** [comment]
If one consider Ka/Ks ratio of > 1 as positive selection yes.

Anyhow, normally one at least should look at a distribution of Ka/Ks values of your query species and compare with this distribution. Since I am not an expert in mito evolution at least you could also look into another published data set and compare to the signatures that have been found in another independant data set.

**Comment by kullrich** [comment]
Since this issue is not related to kakscalculator2 anymore, I am closing this issue here now.

Best regards

**Comment by karthickbrlab** [comment]
hi..

So how could I cite MSA2dist??

**Comment by kullrich** [comment]
Ullrich K (2023). MSA2dist: MSA2dist calculates pairwise distances between all sequences of a DNAStringSet or a AAStringSet using a custom score matrix and conducts codon based analysis. [doi:10.18129/B9.bioc.MSA2dist](https://doi.org/10.18129/B9.bioc.MSA2dist), R package version 1.6.0, https://bioconductor.org/packages/MSA2dist.

**Comment by karthickbrlab** [comment]
Thanks
